### ISSUE TITLE
Tracker "uncostrained movement" is constrained

### ISSUE THREAD

**Issue by net127** [satnogs/satnogs-rotator#2]
Either the cable(s) going to the tracking mechanism or the life of the battery in the tracking mechanism constrain it's movement.

Please consider adding electric brushes to provide power to the tracking mechanism enclosed computer, RTL-SDR, WiFi, stepper motors and motor controllers.

**Comment by Highcooley** [comment]
I'm working on a solution with copper wire commutators and metal strip brushes. I'll let you know as soon as I have a prototype uploaded to my fork.
