### ISSUE TITLE
number of L102 t-slot is wrong in BOM

### ISSUE THREAD

**Issue by cshields** [satnogs/satnogs-rotator#30]
The BOM lists 16x T slot 20x20 L102..  When you add the additional support for the worm gear there are 9 needed for each axis, so the BOM should be updated to say 18 L102.

**Comment by zisi** [comment]
Hey, here is updated https://github.com/satnogs/satnogs-rotator/blob/master/satnogs-mechanical-bom.ods

**Comment by cshields** [comment]
Ahh thanks zisi I must have been using an old bom..
