### ISSUE TITLE
v3 leaflet

### ISSUE THREAD

**Issue by ppapadeas** [satnogs/satnogs-rotator#32]
In A4 format, with complete specs and exploded views

**Comment by ppapadeas** [comment]
First take on Inkscape here https://github.com/satnogs/satnogs-org/blob/master/Assets/v3-leaflet.svg

**Comment by zisi** [comment]
Front
https://community.satnogs.org/uploads/default/original/1X/bf787ecf59a103f0d1e6942d549e6d7974f570df.pdf

Back
https://community.satnogs.org/uploads/default/original/1X/e0331b9eac01764b76bcda2e0c119856b5f5f8f2.pdf
