### ISSUE TITLE
Design portable 6-Element Yagi v2

### ISSUE THREAD

**Issue by boctok01** [satnogs/satnogs-rotator#7]
For portable (and not) operations we need a 6 Element 2m 50Ω Yagi with total boom of 200 cm

**Comment by boctok01** [comment]
Please confirm 6-element 200m 4mm dimensions from http://dk7zb.darc.de/PVC-Yagis/6-Ele-2m.htm

**Comment by ppapadeas** [comment]
@acinonyx , @boctok01 designed v2 of Yagi VHF. Please review here https://github.com/satnogs/satnogs-hardware/tree/master/Antennas/Yagi/Yagi-VHF-v2 as per 6ad5024caa6f4851d5a046b4e1cfbba559ca221e and 41baa80d97da5e6562739933e97da641aae30cf5
